version: 2
updates:
- package-ecosystem: nuget
  directory: "/" # *.sln file used to resolve *.csproj files
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10